### PR TITLE
Gather the agent-pipeline design docs into one folder

### PR DESCRIPTION
**Pull request by hackerwins**
## Summary

Six design docs describe one subject — the loop that takes work from *somebody
noticed something* to *a pull request a human merges* — and they were scattered
through `## Common`, a table of thirty unrelated rows, with the doc meant to be
their entry point sitting between two of the docs it governs.

They move to `docs/design/agent-pipeline/` under a README section of their own:

```
docs/design/agent-pipeline/
├── agent-pipeline.md          ← renamed from agentic-dev-loop.md (umbrella)
├── harness-engineering.md  hunter-usage.md  eval-harness-usage.md
├── debug-report.md  agentic-office-workflow.md
└── walkthrough/{index,deck,tutorial}.html
```

The umbrella takes the bare folder name, matching `board/board.md` and
`notes/notes.md`. The three Korean walkthrough pages that lived in
`docs/design/agentic-dev-loop/` move with it as `walkthrough/` — which is what
**removes** the name collision rather than managing it. Five of the six docs keep
their filenames: renaming `debug-report.md` alone would churn 34 source-comment
references for no reader's benefit, and `sheets/` is precedent for a folder whose
members carry no prefix.

### A structural defect fixed in the same window

`agent-pipeline.md`'s `## Proposal Details` spine ended at line 136, leaving four
body sections as *siblings* of it with two `---` rules papering over the break.
A consequence: the components table cited `see §4`, and the numbering stopped at
§3. The sections are re-parented under the existing numbering (§4, §4.1, §5, §6)
and the cite resolves. **No prose changed** — the five tables, the ASCII diagram,
the `## Goals / Non-Goals` merge and the H2 `## Risks and Mitigation` are all
house dialect and stay.

### Two bindings no link check would have caught

- `harness.config.json` — the entropy advisory is keyed on an exact
  designDir-relative path. Left stale, it stops matching and turns
  `harness-engineering.md`'s *deliberate* "there is no `mixed-controls.tsx`"
  into a blocking `verify:entropy` finding on the next run.
- `.github/CODEOWNERS` — fails **silently**: no CI error, the maintainer-review
  requirement on `harness-engineering.md` just disappears.

Also corrects `review-panel.mjs`'s note that nested design docs are unchecked —
already false (`listDesignDocs` recurses), and the move changes the counts it
quotes. Its paired test had pinned the wrong claim, so those assertions are
inverted with it.

## Deliberately not done

`harness-engineering.md` and `eval-harness-usage.md` are **not** normalized to
`template.md`. They deviate further than `agent-pipeline.md` did, but they
deviate *by genre* — a 3,677-line phase roadmap and an operator runbook are not
design proposals, and forcing them into that skeleton would make them worse.
Recorded in the task notes so the gap stays findable.

`docs/design/design-editor/` is not merged in: it has its own README section, its
own `harness.config.json` advisory pattern, and the links are one-directional.

## Test plan

- `pnpm verify:fast` green.
- `verify:doc-links`, `verify:doc-index`, `verify:entropy` each green on their own.
- Repo-wide grep for the six old paths returns **zero** hits, excluding
  `docs/tasks/archive/**` (frozen by `verify-doc-links.mjs`'s `FROZEN` regex) and
  this task's own two plan files, which cite the old paths as the record of what moved.
- All 12 relative `src`/`href` targets in the three walkthrough pages resolve.
- `/self-review`: 2 rounds, stopped early on a clean round. Round 1's one
  blocking finding (`blast-radius`) was real — `walkthrough/deck.html` still
  reached the design-editor screenshot with `../design-editor/images/`, correct
  from the old location and a broken link from one level deeper. Fixed in
  `0b632df8`. Round 2: all six lenses clean.

## Known limitations

- `docs/tasks/active/20260904-class-b-backend-endpoints-todo.md:37` cites
  `agentic-office-workflow.md:215`. The path was repointed; the **line number**
  was not re-verified against the moved file.
- `verify:entropy` reports 84 advisory broken refs repo-wide — pre-existing and
  unrelated.
- A working tree installed before `ffefac01e` fails `verify:entropy` inside knip
  with `Cannot find module '@sentry/vite-plugin'`. `pnpm install --frozen-lockfile`
  fixes it; no manifest is modified.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01RrsVLxZawZwuMNVuA13QTN

## Summary by CodeRabbit

* **Documentation**
  * Reorganized agent-pipeline design documentation into a dedicated section for easier navigation.
  * Updated internal documentation links and references to reflect the new structure.
  * Added an English walkthrough tutorial covering the Design Editor and Debug Reporter workflows.
  * Translated the existing walkthrough landing page and slide deck into English.
  * Corrected broken cross-references and clarified related design and task documentation.
* **Chores**
  * Synchronized documentation references across development guidance, CI notes, and project metadata.

### CODE REVIEW

File: docs/design/agent-pipeline/walkthrough/index.html [hunk 1]
```diff
@@ -130,69 +130,69 @@
...
-      <li>저장소를 <strong>클론</strong>(복사가 아니라)해 둘 것 — <code>origin</code>이 없으면 PR 단계에서 멈춥니다.</li>
-      <li><strong><code>pnpm design</code>을 세션 전에 한 번 실행</strong>해 볼 것.<br/>첫 설치 약 2분, WSL2에서는 첫 씬 로드가 1분 가까이 걸립니다.<br/>미리 해 오면 세션에서 기다릴 일이 없습니다.</li>
-      <li>pnpm · Docker · 데이터베이스 · GitHub CLI는 <strong>필요 없습니다.</strong></li>
+      <li><strong>Node 22 or newer</strong> and <strong>git</strong>, plus <code>git config user.name</code> / <code>user.email</code> (they will be making commits)</li>
+      <li><strong>Clone</strong> the repository — not a copy of it. Without an <code>origin</code>, the PR step goes nowhere.</li>
+      <li><strong>Run <code>pnpm design</code> once before the session.</strong><br/>The first install takes about 2 minutes, and on WSL2 the first scene load takes close to a minute.<br/>Getting it out of the way means nobody waits during the session.</li>
+      <li><strong>Nothing to install yourself</strong> — no pnpm, Docker, database or GitHub CLI. <code>pnpm design</code> prepares pnpm on a machine that does not have it, and the editor's scenes answer their own data requests from fixtures.</li>
```
[the remark this answers is not in the document]
Comment (hackerwins) [reply docs/design/agent-pipeline/walkthrough/index.html]: Confirmed against `scripts/design-pr.mjs` and fixed in `d8b0dc41e`.

The code is specific about it. With no `gh`, rung 1 (`:351-367`) pushes to `origin` and opens the compare page — but if that push is refused it `stop()`s with *"You probably need your own fork. Install the GitHub CLI … it can make one for you."* Rung 2 (`:369-377`) is the only path that forks, and it is gated on `ghReady`. So `gh` is optional exactly when you can push to `origin`.

That matters more here than the finding says: this page is written for session attendees cloning the repository, who do **not** have push access — so for its actual audience `gh` is required, not optional. The bullet now splits in two, and `deck.html` names `design-pr` as the exception to that card's "nothing else needed" claim.
